eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka
   instance:
    preferIpAddress: true
spring:
 application:
  name: consumerservice
server:
 port: 8084
resilience4j:
 retry:
  instances:
   producer:
    max-attempts: 5
  instance:
   producerPort: 
    max-attempts: 6


